### ISSUE TITLE
Reboot Intercom on user logout

### ISSUE THREAD

**Issue by matanlb** [nhagen/react-intercom#13]
Hi there,
It seems that the component does not support user-logout from the system.
according to [Intercom's docs](https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/the-intercom-javascript-api) in case of a user logoff intercom needs to be shutdown and booted again in order to remove previous conversations.

This is aseptically important for sites using both 'Support' & 'Acquire' since this moves intercom from 'Support' mode to 'Acquire' (the opposite is performed automatically the first time a user_id or email introduced).

Is there a plan to support this kind of behavior?

**Comment by nhagen** [comment]
Interested to know how you're considering using `react-intercom`. We handle this by using the component on two different branches of our application: `/app` and `/marketing` essentially. So when you go from marketing to the logged in version of the site, intercom shutsdown and boots again, regardless of login status.

This prompts me to wonder if there is any reason to recommend *against* that behavior. and whether that is compatible with public sites that have logins (or would that use case make this moot?).

Does that work for you? This behavior could be added to the API, but I'm not sure that managing it explicitly is better than letting it happen automatically depending on your routes. Interested to know how this relates to your use case.

**Comment by matanlb** [comment]
In our specific case we have 3 brunches and only contains Intercom.
Our pre login pages on that branch do not share a common higher order component, so we would have needed to either add it to several parent components, or create a logical parent for all non logged-in pages for this purpose alone.

We do have a root parent for that entire branch so it made sense for us to put it there, wrapping it in a component that supplies the required info and also preforms the shutdown/restart commands in case the logged in/out state changed.

Regarding if this is a better then the current behavior is an interesting question.
I assume the only differences are that the component could be added to higher order components and that the instead of deleting Intercom from `window` and re-running the snippet, a boot command could be passed in instead.

**Comment by nhagen** [comment]
> I assume the only differences are that the component could be added to higher order components

Can you elaborate on this? What I want to avoid is something like a designated prop like `loggedIn`, which feels weird when its value is false while user info is being passed--this kind of leans away from  a single source of truth, which should be the intercom settings.

One solution I see is checking in `componentWillRecieveProps` whether the intercom user settings exist and are being removed, and if so, restart. Does that work for you? I'll need to go back and confirm with Intercom documentation that this makes sense though.
