### ISSUE TITLE
Acquire Issues

### ISSUE THREAD

**Issue by jeremy-myRise-house** [nhagen/react-intercom#24]
This may or may not pertain this code base, but I'm currently using the react-intercom in my React app, However I'm seeing issues with it not recognizing its location. For instance I have set up with Intercom a Acquire message that says, if you have visited '/stories' URL pathname more then 2, send a message to this visitor. My conversations with Intercom have pointed to the non registering being because my app is a single page application. When I look at the network data in the console. I can see the Intercom 'ping' being send just once when I visit the '/stories' path, is this more a React lifecycle issue or? Any thoughts or suggestions?

**Comment by vernondegoede** [comment]
I'm experiencing the same issue. There's an error message stating 

```
XMLHttpRequest cannot load https://api-iam.intercom.io/ping. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 429.
```

Might be related to https://github.com/gdi2290/angular-intercom/issues/30

**Comment by nhagen** [comment]
Did you guys find a resolution for this? Not sure how this library would be the problem.

Related https://github.com/nhagen/react-intercom/issues/42
