### ISSUE TITLE
[Question] Can i call arbitrary API endpoints from this library?

### ISSUE THREAD

**Issue by dcworldwide** [nhagen/react-intercom#28]
Can i call arbitrary API endpoints from this library?

I.e. the tags endpoint. 

I'm trying to assign tags to users.

**Comment by Dorian** [comment]
Totally doable with their API

https://developers.intercom.com/v2.0/reference#tag-or-untag-users-companies-leads-contacts

**Comment by nhagen** [comment]
That is to say, this is their JS library, which provides their [JS API](https://developers.intercom.com/v2.0/docs/intercom-javascript), not their [general API](https://developers.intercom.com/v2.0/reference)

**Comment by dcworldwide** [comment]
OK got it thanks
