### ISSUE TITLE
No release history

### ISSUE THREAD

**Issue by mmaday** [nhagen/react-intercom#32]
It's not the most pressing issue, but if you leverage the git tags, you'll get a release history on the release tab (https://github.com/nhagen/react-intercom/releases).  You'll need to retroactively tag each commit where you updated the package.json release version.

Thanks for the useful project!

**Comment by nhagen** [comment]
Hey, thanks for bringing this up. I'd definitely like to do this and will spend some time on it next time I push a non-critical release. In the meantime I'm being very careful not to make any API changes/only patch updates, so everyone should be fine using the latest.

On that note, if someone finds themselves depending on a bug that I'm unaware of please let me know!

**Comment by nhagen** [comment]
I haven' maintained this package super well, after #73 this should be a addressed by a commit hook requiring more formal change details in each commit.
