### ISSUE TITLE
IntercomSettings persist on window object after shutdown

### ISSUE THREAD

**Issue by michaelReyder** [nhagen/react-intercom#39]
After attempting to use this component, I noticed that there was some strange behaviour happening in my Intercom dashboard. Without going too deep into the details, I noticed that even after Intercom is shut down, the **_IntercomSettings_** property on the window object remains there.

In your code, within the **_componentWillUnmount_** lifecycle hook you delete the **_window.Intercom_** property after running **_window.Intercom('shutdown')_**, but you never delete the **_window.IntercomSettings_**.

**Comment by nhagen** [comment]
Fixed https://github.com/nhagen/react-intercom/commit/d34ecda87028601075795ae8f73bf2bf5926d386
