### ISSUE TITLE
Not working on production build created with create-react-app 

### ISSUE THREAD

**Issue by deepeshsunku** [nhagen/react-intercom#45]
Hi,

I'm running this on a sample app using React's create-react-app. It works when I do `npm start` and try to view the app on my localhost. But it doesn't work once I create a production build using `npm run build`. I get this error when I run the production build using `pushstate-server build`:
`TypeError: null is not an object (evaluating 'document.body.appendChild')`. 

Any suggestions?

**Comment by nhagen** [comment]
Sorry, its been a while. Hopefully you got past this!

In a fresh CRA app, I'm able to run `yarn deploy` and `now ./build` and it to works.

https://build-vngoamgoxm.now.sh/

Did you figure out what the issue was?
