### ISSUE TITLE
Question: does this Intercom('update') on browser URL changes via React Router

### ISSUE THREAD

**Issue by bradical** [nhagen/react-intercom#47]
From [here](https://docs.intercom.com/install-on-your-product-or-site/other-ways-to-get-started/integrate-intercom-in-a-single-page-app):

> For single paged apps or pages where the URL changes without a full page reload, the Intercom Messenger does not automatically send URL changes to Intercom to match messages based on URLs. You will need to call Intercom("update") in order to initiate a "ping" every time a URL changes.

**Comment by bradical** [comment]
Hi @fertech, this is how we've got ours implemented at the moment.

In our main App component we have the following utility methods:

```
  updateIntercom = () => {
    if (!process.env.NODE_ENV || process.env.NODE_ENV === 'development')
      return;

    window.Intercom('update');
  }

  bootIntercom = (user) => {
    if (!process.env.NODE_ENV || process.env.NODE_ENV === 'development')
      return;

    if (user && user.id) {
      window.Intercom('boot', {
        app_id: 'ndutusm1',
        name: user.name,
        email: user.email,
        user_id: user.id,
        created_at: Math.floor(new Date(user.created_at).getTime() / 1000),
      });
    }
    else {
      window.Intercom('boot', {app_id: '<INTERCOM_APP_ID>'});
    }
  }
```

which we're then calling from:

App's `componentWillMount`:

```
  componentWillMount() {
    this.unlisten = this.props.history.listen((location, action) => {
      this.updateIntercom();
    });
  }
```

And booting from a method `componentDidMount` when the user is authenticated:

```
  componentDidMount() {
    if (authenticator.isAuthenticated === true)
      this.loadDefaultsAndUserContext();
  }
```

Your situation may be different but that callback to `updateIntercom` in `componentWillMount` was the piece we had to figure out on our with using React Router.

**Comment by nhagen** [comment]
This library does not attempt to do any integrations with projects such as `react-router`. @bradical's guide above looks like it should work, except `componentWillMount` is deprecated, so I would not recommend that part--instead you could use `componentDidMount` or `constructor`. But listening on `history.listen` is perfectly valid.

I would recommend something like this as the idiomatic way, leveraging the immutable `location` object provided by `react-router` v4:

```
class App extends React.Component {
  componentDidUpdate ({ location: oldLocation }) => {
    const { location: newLocation } = this.props;
    if (newLocation !== oldLocation) {
      window.Intercom('update');
    }
  }

  render () { ... }
}

export component withRouter(App);
```
