### ISSUE TITLE
Incorrect documentation?

### ISSUE THREAD

**Issue by olalonde** [nhagen/react-intercom#5]
```javascript
<Intercom appID="az33rewf" userID={ user.id } otherUserProp={ user.otherUserProp } />
```

should be 

```javascript
<Intercom appID="az33rewf" settings={{ user_id: user.id, email: user.email, name: user.name }} />
```

Well, at least according to that line:

```
    window.intercomSettings = { ...props.settings, app_id: appID };
```

Right?

**Comment by nhagen** [comment]
Looks like I was hasty meging in a pull request that changed the API. That change shouldn't occur without a major version bump, and I'm not sure its necessary at this point. I've reverted the API change so that 

```
<Intercom appID="az33rewf" userID={ user.id } otherUserProp={ user.otherUserProp } />
```

is correct again.

Thanks for pointing this out!

**Comment by olalonde** [comment]
Thanks.
