### ISSUE TITLE
unable to send user details to intercom

### ISSUE THREAD

**Issue by distroyq** [nhagen/react-intercom#50]
```
    const user = {
      email: this.props.email,
      name: this.props.fullName,
      company: 'aaaa',
    };

    return (
      <div className="app">
        <div>
          <Intercom appID="xxxxxx" {...user} />
    ......
```

i still see that the "company" attribute in the user's profile page is Unknown

thanks!

**Comment by nhagen** [comment]
Were you able to resolve this? Sometimes it may take a few minutes for information about a user to show up in the Intercom interface, but in general I have not had trouble testing this feature.

**Comment by gautamsawhney** [comment]
For anyone who comes here, you need to pass `company` as an object

    const user = {
      user_id: userId,
      email: email,
      name: employeeName,
      company: {
        company_id: companyId,
        name: companyName,
        size: companySize,
        website: websiteUrl
      }
    };
