### ISSUE TITLE
Callbacks for IntercomAPI?

### ISSUE THREAD

**Issue by RyanWarner** [nhagen/react-intercom#51]
Is there any way to know if a call to the IntercomAPI (for example, `IntercomAPI('update', { email: email.value })`) has succeeded or failed?

I can't find anything in the Intercom docs or here. How do people handle this?

Thanks!

**Comment by nhagen** [comment]
I haven't heard of any API for this. If you really wanted to, you could probably leverage some undocumented API in `window.Intercom`, but I wouldn't necessarily recommend that. If you're having issues sending data, Intercom's own support is usually very responsive.
