### ISSUE TITLE
IntercomAPI can no longer be imported

### ISSUE THREAD

**Issue by pingshunhuang** [nhagen/react-intercom#58]
Due to this change...

https://github.com/nhagen/react-intercom/commit/ca2f2dbf5f479d86f1407ca7edcb2620959dcab2

**Comment by mattieruth** [comment]
@pingshunhuang do you have a workaround for this issue?

**Comment by pingshunhuang** [comment]
@mattieruth I can't find a workaround. I just use `1.0.14` where things seem to work

**Comment by nhagen** [comment]
This should be addressed in #73.
