### ISSUE TITLE
Add SSR rendering support

### ISSUE THREAD

**Issue by thomasdavis** [nhagen/react-intercom#6]
Hi there, cool lib! Would love to use it but we render our app on the server and get this error upon trying to start the app

```js
ReferenceError: window is not defined
  at Object.<anonymous> (/web/node_modules/react-intercom/lib/index.js:24:41)
```

I imagine simply adding some simple protection would be fine.

**Comment by nhagen** [comment]
Since this is something we should be doing anyways, I added it. Let me know if it works for you in the `1.0.8`.

**Comment by thomasdavis** [comment]
@nhagen Thank you very much, will try later!
