### ISSUE TITLE
customise the styling of intercom

### ISSUE THREAD

**Issue by tanakachitsamba** [nhagen/react-intercom#66]
Hi, I was wondering if there was a way of customing the styling the intercom so that we can add our company branding

**Comment by quantafire** [comment]
I was wondering the same. As per this page: https://www.intercom.com/help/configure-intercom/customize-the-intercom-messenger/customize-the-intercom-messenger-technical

**Comment by nhagen** [comment]
If this was not supported by 1.0, this should definitely be supported in 2.0. See #73 for more details, and let me know if you're able to do what you need to do using that version.

You should now be able to pass options like this:

```js
        <ReactIntercom
          app_id="xsdvb1w1"
          vertical_padding="400"
          action_color="purple" />
```
