### ISSUE TITLE
Receiving multiple 'rate_limited_update' errors in console

### ISSUE THREAD

**Issue by dj9aj** [nhagen/react-intercom#70]
Hello all,
We've been using react-intercom within our web app for over a year now, but since yesterday we've started receiving multiple errors in the console on every network request made. They're also causing massive performance issues. The 'rate_limited_update' red error points towards a minimised intercom script. From what I can see online, if a rate limit is exceeded, then a 429 error is given. I can see that the 'ping' network requests/responses from intercom clearly state that we're not close to exceeding our rate limit, and the response codes are all 200.

I've attached screenshots of the error in our console, and also the status code we receive, along with the rate limiting details that intercom provide within the response.

<img width="563" alt="Screenshot 2019-07-11 at 09 17 31" src="https://user-images.githubusercontent.com/29177797/61034288-e3a60c00-a3bc-11e9-9b38-71ddaddbfb45.png">
<img width="480" alt="Screenshot 2019-07-11 at 09 18 04" src="https://user-images.githubusercontent.com/29177797/61034300-e99bed00-a3bc-11e9-9878-37a738b83dbe.png">
<img width="528" alt="Screenshot 2019-07-11 at 09 18 27" src="https://user-images.githubusercontent.com/29177797/61034312-ebfe4700-a3bc-11e9-97ea-ce66d28515a3.png">

Has anyone else experienced this? Any help would be much appreciated!

Thanks,

Jack

**Comment by tiosalazar** [comment]
I have the same problem did you found any solution ?

![image](https://user-images.githubusercontent.com/12763760/61162659-35d75200-a4cf-11e9-84f8-960a96cc5d8d.png)

**Comment by u-ashish** [comment]
+1 also experiencing this, albeit with `ng-intercom`. Might be an `intercom` related issue instead of the client wrappers we're using...

**Comment by prernajain21** [comment]
+1, experiencing the same issue

**Comment by dj9aj** [comment]
No solution yet. I've been in touch with Intercom via their web app. One of their engineers replied over the weekend, and they were not aware of this issue. I'll keep this thread updated if and when I hear any more news!

**Comment by renatohlf** [comment]
+1, same for me.

**Comment by dj9aj** [comment]
An engineer from Intercom has informed me that the issue is a priority for them to fix.

**Comment by tiosalazar** [comment]
Hello for everybody, any knows if the problem was resolved ?

**Comment by dj9aj** [comment]
Yes, Intercom has resolved this issue their end.
