### ISSUE TITLE
Access to `Intercom('show');` Function

### ISSUE THREAD

**Issue by toddgower-hiatus** [nhagen/react-intercom#78]
Does this library provide access to Intercom functions that control when/how the messenger is presented? Can I simply call them using the `IntercomAPI` via `import { IntercomAPI } from 'react-intercom';`?

**Comment by Redfern** [comment]
It appears you can, i've just used the IntercomAPI method and it works fine.

e.g.

```
IntercomAPI('onShow', () => {
      // do something
});
```
```
IntercomAPI('show')
```

**Comment by toddgower-hiatus** [comment]
This was asked without full understanding of the lib. Closing...
