### ISSUE TITLE
Unable to see intercom messenger

### ISSUE THREAD

**Issue by mding5692** [nhagen/react-intercom#90]
Unable to see intercom messenger but was able to load it properly couple days ago on the production web app and also the development environment and verified that the appId is correct, I think this might have something to do with recent samesite cookie updates for browsers?

**Comment by mding5692** [comment]
I'm also just using it like this right now: 
`            {this.state.intercomUserData &&
              <Intercom appID={app_id}
                {...this.state.intercomUserData}
              />
            }

            {!this.state.intercomUserData &&
              <Intercom appID={app_id} />
            }`

**Comment by mding5692** [comment]
Fixed this by moving to using intercom's hacky but recommended way of doing it for single-page apps, see the links I used below:
https://www.intercom.com/help/en/articles/170-integrate-intercom-in-a-single-page-app
https://www.intercom.com/help/en/articles/168-install-intercom-on-your-web-app-for-logged-in-users
https://www.intercom.com/help/en/articles/167-install-intercom-on-your-website-for-logged-out-visitors

**Comment by devrnt** [comment]
I'm keen to announce that I've released a React Intercom integration:   
https://github.com/devrnt/react-use-intercom

I don't want to spam this issue with advertisement, that's why I'll delete this message in the near future.

**Motivation**
I've found it not very developer friendly to integrate Intercom in a React application.

**Comment by mding5692** [comment]
Ok will take a look much thanks, seems like this repo is not maintained anymore
